# Description: Configuration file for Faster R-CNN model
project_name: 'faster_rcnn18'
log_dir: 'logs'
log_interval: 10
checkpoint_interval: 5

# Data configuration
dataroot: 'data'
train_data: 'train'
val_data: 'valid'
test_data: 'test'

# Model configuration
model: 'faster_rcnn'
pretrained_model_path: 'checkpoints/resnet18_best.pth'
backbone: 'resnet18'
num_classes: 22
img_height: 640
img_width: 640

# Training configuration
batch_size: 4
num_epochs: 2
learning_rate: 0.001
optimizer: 'SGD'
momentum: 0.9
weight_decay: 0.0005
lr_scheduler: 'linear'
step_size: 5
gamma: 0.1

# Active learning configuration
active_learning_epochs: 5
unlabel_data: 'unlabel'
sampling_num: 10
active_learning_strategy: 'least_confidence'
score_threshold: 0.999

# Device configuration
device: 'gpu'